
---
- hosts: web
  become: true
  tasks:
    - name: Установка Apache и PHP
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - apache2
        - php
        - libapache2-mod-php
        - php-mysql

    - name: Установка MySQL
      apt:
        name: mysql-server
        state: present

    - name: Загрузка Wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz

    - name: Распаковка Wordpress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
